builds:
  - main: main.go
    binary: helm-freeze
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
archives:
  - format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
brews:
  -
    name: helm-freeze
    goarm: 6
    repository:
      owner: qovery
      name: homebrew-helm-freeze
    url_template: "https://github.com/Qovery/helm-freeze/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    commit_author:
      name: Pierre Mavro
      email: pmavro@qovery.com
    directory: Formula
    homepage: ""
    description: "Freeze your charts in the wished versions"
    skip_upload: false
scoops:
  -
    url_template: "https://github.com/Qovery/helm-freeze/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    repository:
      owner: qovery
      name: scoop-helm-freeze
    commit_author:
      name: qovery
      email: contact@qovery.com
    homepage: "https://docs.qovery.com"
    description: "Freeze your charts in the wished versions"
    license: GPL3
